-- Simple multi-item order storage without JSON.
-- Run this in Supabase SQL Editor after bb_orders already exists.
-- One bb_orders row = order header; one bb_order_items row = one product line.

create table if not exists public.bb_order_items (
  id bigint generated by default as identity primary key,
  order_key text not null,
  order_number text,
  line_no integer not null default 1,
  sku text,
  th_name text,
  label_display text,
  display_for_packer text,
  emoji text,
  quantity numeric not null default 1,
  unit_price numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bb_order_items_order_line_unique unique (order_key, line_no)
);

create index if not exists bb_order_items_order_key_idx
  on public.bb_order_items (order_key, line_no);
create index if not exists bb_order_items_order_number_idx
  on public.bb_order_items (order_number, line_no);
create index if not exists bb_order_items_sku_idx
  on public.bb_order_items (sku);

-- Backfill one legacy product per existing order. This is safe to re-run because
-- the unique key prevents duplicate line 1 rows. Only orders with an explicit
-- COD value are admitted; the page has already summarized and confirmed them.
insert into public.bb_order_items (
  order_key, order_number, line_no, sku, th_name, label_display,
  display_for_packer, emoji, quantity, unit_price
)
select
  coalesce(nullif(upsert_key, ''), nullif(order_number, ''), 'id:' || id::text),
  order_number,
  1,
  sku,
  th_name,
  display_label,
  display_for_packer,
  emoji,
  coalesce(nullif(qty, 0), 1),
  null
from public.bb_orders o
where (
    sku is not null
    or th_name is not null
    or display_label is not null
    or display_for_packer is not null
  )
  and coalesce(cod_amount, expected_cod) is not null
on conflict (order_key, line_no) do nothing;

comment on table public.bb_order_items is
  'One row per product line belonging to an order in bb_orders. This replaces items_json.';
comment on column public.bb_order_items.order_key is
  'Matches bb_orders.upsert_key, then order_number, then id:<id>.';
