import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { readAlienReview } from "@/lib/canonical";
import { AlertTriangle, BrainCircuit, CheckCircle2, RefreshCw, Search, XCircle } from "lucide-react";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";

function stockLabel(status: string | null | undefined) {
  if (status === "IN_STOCK") return { text: "✅ INSTOCK", tone: "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" };
  if (status === "OUT_OF_STOCK") return { text: "❌ OUT_OF_STOCK", tone: "border-red-400/20 bg-red-400/10 text-red-300" };
  return { text: "⚠️ STOCK_UNKNOWN", tone: "border-amber-400/20 bg-amber-400/10 text-amber-200" };
}
function money(value: unknown) { return value == null || value === "" ? "—" : `${Number(value).toLocaleString("th-TH", { maximumFractionDigits: 2 })} ฿`; }

export default function AlienRoom() {
  const [search, setSearch] = useState("");
  const query = useQuery({ queryKey: ["alien-review", search], queryFn: () => readAlienReview(search), refetchInterval: 30_000 });
  const rows = query.data ?? [];
  const missing = rows.filter(row => row.audit_status === "RAW_MISSING").length;
  const rawEqualsSku = rows.filter(row => row.audit_status === "RAW_EQUALS_SKU").length;
  const matched = rows.filter(row => row.audit_status === "MATCHED" || row.audit_status === "APPROVED").length;
  const unknown = rows.filter(row => row.stock_status === "STOCK_UNKNOWN").length;
  const mismatch = rows.filter(row => row.price_mismatch).length;
  return <div className="min-h-[calc(100vh-2rem)] space-y-5 bg-[#09070d] p-2 text-white sm:p-4 lg:p-6">
    <header className="rounded-3xl border border-fuchsia-400/20 bg-[#100c19] p-6 shadow-2xl shadow-fuchsia-950/20"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-fuchsia-300"><BrainCircuit className="h-4 w-4" /> ALIEN INBOX · RAW EVIDENCE</div><h1 className="mt-3 text-3xl font-semibold">ห้องเอเลี่ยน · ตรวจคำดิบและคลัง</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-violet-100/55">ออเดอร์เข้าได้เสมอ ห้องนี้ใช้ตรวจ raw, SKU, Product Master, ราคา และสถานะคลัง โดยไม่แก้ COD จริงและไม่บล็อก Flow</p></div><div className="flex gap-2"><Link href="/aliases"><Button variant="outline" className="border-fuchsia-400/20 bg-fuchsia-400/5 text-fuchsia-100">ไปห้อง Alias</Button></Link><Button variant="outline" onClick={() => query.refetch()} className="border-violet-400/20 bg-violet-400/5 text-violet-100"><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} />รีเฟรช</Button></div></div></header>
    {query.isError ? <Card className="border-red-400/25 bg-red-950/20"><CardContent className="p-5 text-sm text-red-200">อ่านห้องคำวิบัติไม่สำเร็จ: {query.error instanceof Error ? query.error.message : String(query.error)}</CardContent></Card> : null}
    <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Metric label="รายการทั้งหมด" value={rows.length} tone="text-white" /><Metric label="จับคู่แล้ว" value={matched} tone="text-emerald-300" /><Metric label="คำดิบหาย" value={missing} tone="text-red-300" /><Metric label="Raw เป็น SKU" value={rawEqualsSku} tone="text-amber-300" /><Metric label="คลังไม่ทราบ" value={unknown} tone="text-amber-200" /><Metric label="ราคาต่าง" value={mismatch} tone="text-orange-300" /></div>
    <Card className="rounded-3xl border-violet-500/15 bg-[#100d15]"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="text-base">หลักฐานคำสินค้าและผลเชื่อมจริง</CardTitle><div className="relative w-full sm:w-96"><Search className="absolute left-3 top-2.5 h-4 w-4 text-violet-100/30" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="ค้นหาคำวิบัติ, SKU, สถานะ…" className="border-violet-500/15 bg-black/20 pl-9 text-white placeholder:text-violet-100/25" /></div></div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[1500px] text-left text-xs"><thead className="border-b border-violet-500/10 text-violet-100/35"><tr><th className="p-3">ค่าย</th><th className="p-3">คำดิบลูกค้า</th><th className="p-3">SKU</th><th className="p-3">ชื่อ/Display จาก Master</th><th className="p-3">จำนวนสั่ง</th><th className="p-3">ราคาต่อหน่วย</th><th className="p-3">คลังเหลือ</th><th className="p-3">สถานะคลัง</th><th className="p-3">สถานะแมป</th><th className="p-3">ตรวจราคา</th></tr></thead><tbody>{rows.map(row => { const status = row.audit_status; const bad = status === "RAW_MISSING" || status === "RAW_EQUALS_SKU"; const stock = stockLabel(row.stock_status); return <tr key={`${row.id ?? row.order_id}-${row.line_no}`} className="border-b border-violet-500/[0.06] align-top"><td className="p-3 font-mono text-[10px] text-fuchsia-200">{row.store_code || "—"}</td><td className="max-w-xs whitespace-pre-wrap p-3 font-medium text-fuchsia-100">{row.raw_display}</td><td className="p-3 font-mono text-cyan-200">{row.sku || "CHECK_SKU"}</td><td className="max-w-xs whitespace-pre-wrap p-3 text-emerald-200">{row.mapped_display || "ยังไม่มี Master"}</td><td className="p-3 text-amber-200">{row.quantity ?? "—"}</td><td className="p-3 text-fuchsia-200">{money(row.unit_price)}</td><td className="p-3 text-slate-300">{row.available_qty ?? row.stock_qty ?? "—"}</td><td className="p-3"><Badge className={stock.tone}>{stock.text}</Badge></td><td className="p-3"><Badge className={bad ? "border-amber-400/20 bg-amber-400/10 text-amber-200" : status === "MATCHED" ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-violet-400/20 bg-violet-400/10 text-violet-200"}>{bad ? <><AlertTriangle className="mr-1 inline h-3 w-3" />{status}</> : status === "MATCHED" ? <><CheckCircle2 className="mr-1 inline h-3 w-3" />MATCHED</> : <><XCircle className="mr-1 inline h-3 w-3" />{status}</>}</Badge></td><td className="p-3">{row.price_mismatch ? <Badge className="border-orange-400/20 bg-orange-400/10 text-orange-200">⚠️ PRICE_MISMATCH</Badge> : <span className="text-slate-600">—</span>}</td></tr>; })}</tbody></table></div>{query.isLoading ? <p className="p-8 text-center text-sm text-violet-100/40">กำลังอ่านคำดิบ…</p> : null}{!query.isLoading && rows.length === 0 ? <p className="p-8 text-center text-sm text-violet-100/40">ยังไม่พบรายการในฐานค่ายนี้</p> : null}</CardContent></Card>
  </div>;
}
function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <Card className="rounded-2xl border-violet-500/15 bg-[#100d15]"><CardContent className="p-4"><p className={`text-2xl font-semibold ${tone}`}>{value.toLocaleString("th-TH")}</p><p className="text-xs text-violet-100/45">{label}</p></CardContent></Card>; }
