import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { readProductMapAliases, readProductMapCatalog, saveProductMapAlias, type ProductMapAlias } from "@/lib/canonical";
import { Check, Plus, RefreshCw, Tags } from "lucide-react";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";

export default function ProductAliases() {
  const aliasesQuery = useQuery({ queryKey: ["product-map-aliases"], queryFn: readProductMapAliases, refetchInterval: 60000 });
  const catalogQuery = useQuery({ queryKey: ["product-map-catalog"], queryFn: readProductMapCatalog });
  const [alias, setAlias] = useState("");
  const [sku, setSku] = useState("");
  const [label, setLabel] = useState("");
  const [catalogOpen, setCatalogOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const requestedSku = typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("sku") ?? "";
  useEffect(() => { if (requestedSku) { setSku(requestedSku); const found = (catalogQuery.data ?? []).find(item => item.sku === requestedSku); if (found) setLabel(found.label); } }, [requestedSku, catalogQuery.data]);
  const matches = (catalogQuery.data ?? []).filter(item => `${item.sku} ${item.label}`.toLowerCase().includes(sku.toLowerCase())).slice(0, 8);
  const submit = async () => { setSaving(true); setError(""); try { await saveProductMapAlias({ alias, canonicalSku: sku }); setAlias(""); await aliasesQuery.refetch(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setSaving(false); } };
  const grouped = new Map<string, ProductMapAlias[]>(); for (const row of aliasesQuery.data ?? []) grouped.set(row.canonicalSku, [...(grouped.get(row.canonicalSku) ?? []), row]);
  return <div className="min-h-[calc(100vh-2rem)] bg-[#09070d] text-white"><div className="mx-auto max-w-6xl space-y-5 p-2 sm:p-4 lg:p-6">
    <header className="relative overflow-hidden rounded-3xl border border-violet-500/20 bg-[#100c19] px-6 py-7 shadow-2xl shadow-violet-950/20 sm:px-8"><div className="relative"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.24em] text-fuchsia-300"><Tags className="h-4 w-4" /> ALIEN LEARNING · PRODUCT_MAP_MASTER</div><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-semibold tracking-tight">ห้องเอเลี่ยน 2 · เรียนรู้และอนุมัติ Alias</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-violet-100/55">อ่านและบันทึกจาก <span className="font-mono text-fuchsia-200">product_map_master</span> โดยใช้ SKU เดียวกับ Product Master ไม่เรียก public.aliases แล้ว</p></div><Link href="/alien-room"><Button variant="outline" className="border-fuchsia-400/20 bg-fuchsia-400/5 text-fuchsia-100">กลับ Alien Inbox</Button></Link></div></div></header>
    <Card className="rounded-3xl border-violet-500/15 bg-[#100d15]"><CardHeader><CardTitle className="text-base">เพิ่ม Alias เข้า Product Map Master</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-3"><Input value={alias} onChange={e => setAlias(e.target.value)} placeholder="คำดิบ เช่น Mond เขียว" className="border-violet-500/15 bg-black/20 text-white" /><div className="relative"><Input value={sku} onChange={e => { setSku(e.target.value); setCatalogOpen(true); }} onFocus={() => setCatalogOpen(true)} placeholder="เลือก SKU จาก Product Master" className="border-violet-500/15 bg-black/20 text-white" />{catalogOpen && sku && matches.length ? <div className="absolute left-0 right-0 top-12 z-30 max-h-64 overflow-auto rounded-xl border border-violet-400/25 bg-[#1a1224] p-1">{matches.map(item => <button type="button" key={item.sku} onClick={() => { setSku(item.sku); setLabel(item.label); setCatalogOpen(false); }} className="flex w-full justify-between rounded-lg px-3 py-2 text-left text-xs hover:bg-fuchsia-500/15"><span className="text-fuchsia-200">{item.emoji} {item.sku}</span><span className="text-violet-100/60">{item.label}</span></button>)}</div> : null}</div><Input value={label} readOnly placeholder="Display จาก Product Master" className="border-violet-500/15 bg-black/20 text-violet-100/60" /></div><div className="mt-3 flex justify-end"><Button disabled={!alias.trim() || !sku.trim() || saving} onClick={submit} className="bg-gradient-to-r from-fuchsia-600 to-violet-600"><Plus className="mr-2 h-4 w-4" />{saving ? "กำลังบันทึก…" : "เพิ่ม Alias"}</Button></div>{error ? <p className="mt-2 text-xs text-red-300">บันทึกไม่สำเร็จ: {error}</p> : null}</CardContent></Card>
    <Card className="overflow-hidden rounded-3xl border-violet-500/15 bg-[#100d15]"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Alias ที่เชื่อมด้วย SKU</CardTitle><Button variant="outline" size="sm" onClick={() => aliasesQuery.refetch()} className="border-violet-400/20 bg-transparent text-violet-100/70"><RefreshCw className={aliasesQuery.isFetching ? "mr-2 h-3.5 w-3.5 animate-spin" : "mr-2 h-3.5 w-3.5"} />รีเฟรช</Button></CardHeader><CardContent className="space-y-2">{aliasesQuery.isLoading ? <p className="p-8 text-center text-sm text-violet-100/40">กำลังโหลด Product Map Master…</p> : Array.from(grouped.entries()).map(([groupSku, rows]) => <div key={groupSku} className="rounded-2xl border border-violet-500/10 bg-black/15 p-3"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-cyan-200">{groupSku}</span><Badge className="border-emerald-400/20 bg-emerald-400/10 text-emerald-300">{rows.length} Alias</Badge><span className="text-fuchsia-200">{rows[0].canonicalLabel}</span></div><div className="mt-2 flex flex-wrap gap-2">{rows.map(row => <span key={row.id} className="rounded-lg border border-fuchsia-400/15 bg-fuchsia-400/5 px-2 py-1 text-xs text-fuchsia-100">{row.alias}</span>)}</div></div>)}{!aliasesQuery.isLoading && !aliasesQuery.data?.length ? <p className="p-8 text-center text-sm text-violet-100/40">ยังไม่มี Alias ใน product_map_master</p> : null}</CardContent></Card>
  </div></div>;
}
