export type LiveOrderItem = { id?: number; order_id?: number | null; product_id?: number | null; sku?: string | null; th_name?: string | null; product_name?: string | null; label_display?: string | null; emoji?: string | null; extracted_emoji?: string | null; display_for_packer?: string | null; telegram_final_mapped?: string | null; quantity?: number | null; qty?: number | null; extracted_qty?: number | null; unit_price?: number | null; expected_cod?: number | null; stock_qty?: number | null; stock_status?: string | null; raw_product_text?: string | null; raw_product_text_norm?: string | null; mapping_status?: string | null; parser_confidence?: number | null; match_method?: string | null; candidate_skus?: unknown; evidence_sources?: unknown; reject_reason?: string | null };
export type LiveOrder = { id: number; upsert_key: string | null; order_number: string; order_date: string | null; order_time: string | null; order_time_display?: string | null; created_at: string | null; updated_at: string | null; customer_name: string | null; facebook_name: string | null; phone: string | null; full_address: string | null; address_line_1?: string | null; address_line_2?: string | null; district?: string | null; amphoe?: string | null; province?: string | null; zipcode?: string | null; address_display_packer: string | null; page_name: string | null; page_id: string | null; thread_id: string | null; threadId: string | null; recipient_id: string | null; cod_amount: number | null; expected_cod: number | null; sku: string | null; th_name: string | null; emoji: string | null; display_for_packer: string | null; label_display: string | null; telegram_status: string | null; order_status: string | null; audit_status: string | null; audit_flags: string | null; cod_check_status: string | null; is_ready_to_pack: boolean; telegram_message: string | null; telegram_copy_text: string | null; telegram_chat_id: string | null; source_text: string | null; raw_text_with_phone: string | null; raw_text_with_phone_timed: string | null; full_chunk_text: string | null; chat_timeline: string[]; items_json?: unknown; items_text?: string | null; items_count?: number | null; total_quantity?: number | null; items: LiveOrderItem[] };
export type LiveOrderStats = { total: number; mapped: number; review: number; codCheck: number; sent: number; pages: number };
export type LiveThread = { key: string; pageName: string; pageId: string | null; threadId: string | null; customerId: string | null; latestAt: string | null; latestOrderNumber: string; customerName: string | null; preview: string; orderCount: number; unread: boolean; sentCount: number; messageCount: number; customerMessages: number; pageMessages: number; orderSignals: number; snippets: string[]; orders: LiveOrder[]; chatTimeline: string[]; searchText: string };
export type ExternalChatMessage = { id: number; providerMessageId: string | null; source_message_id?: string | null; dedupe_key?: string | null; pageId: string; pageName: string | null; threadId: string; senderId: string; senderName: string | null; customerName: string | null; sender_name?: string | null; customer_name?: string | null; speaker_type?: string; senderType: "customer" | "page"; side: "left" | "right"; direction: "inbound" | "outbound"; text: string | null; message_text?: string | null; attachmentsJson: string | null; occurredAt: string | null; occurred_at?: string | null; source_created_at?: string | null; createdAt: string | null };
export type LiveProductMapping = { sku: string; label: string; price: number | null; emoji: string | null; aliases?: string | null };
export type StockProduct = LiveProductMapping & { id: number; thName: string | null; stockQty: number | null; stockStatus: string | null; status: string | null; updatedAt: string | null };
export type StockWarning = { kind: "duplicate_sku" | "missing_sku"; sku: string | null; label: string | null; count?: number };

function config() { const baseUrl = process.env.SUPABASE_URL?.replace(/\/$/, ""); const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!baseUrl || !key) throw new Error("Supabase secrets are not configured"); return { baseUrl, key }; }
export async function supabaseGet<T>(path: string): Promise<T> {
  const { baseUrl, key } = config();
  const response = await fetch(`${baseUrl}/rest/v1/${path}`, { headers: { apikey: key, Authorization: `Bearer ${key}`, Accept: "application/json" } });
  const body = await response.text();
  if (!response.ok) throw new Error(`Supabase returned HTTP ${response.status} for ${path}: ${body.slice(0, 500)}`);
  try { return JSON.parse(body) as T; } catch { throw new Error(`Supabase returned non-JSON for ${path}: ${body.slice(0, 300)}`); }
}
export async function supabasePost<T>(path: string, body: unknown): Promise<T> { const { baseUrl, key } = config(); const response = await fetch(`${baseUrl}/rest/v1/${path}`, { method: "POST", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(`Supabase returned HTTP ${response.status}: ${(await response.text()).slice(0, 300)}`); return response.json() as Promise<T>; }
function text(v: unknown) { return v == null ? null : String(v); }
function num(v: unknown) { const n = Number(v); return v == null || v === "" || !Number.isFinite(n) ? null : n; }
function bool(v: unknown) { return v === true || v === "true" || v === 1; }
function timeline(v: unknown) { if (Array.isArray(v)) return v.map(String).filter(Boolean); if (typeof v === "string" && v.trim()) { try { const parsed = JSON.parse(v); if (Array.isArray(parsed)) return parsed.map(String).filter(Boolean); } catch {} return v.split("\n").map(s => s.trim()).filter(Boolean); } return []; }
function normalizeItem(r: Record<string, unknown>): LiveOrderItem { return { id: num(r.id) ?? undefined, order_id: num(r.order_id), product_id: num(r.product_id), sku: text(r.sku), th_name: text(r.th_name), product_name: text(r.product_name), label_display: text(r.label_display), emoji: text(r.emoji), extracted_emoji: text(r.extracted_emoji), display_for_packer: text(r.display_for_packer), telegram_final_mapped: text(r.display_for_packer), quantity: num(r.quantity), qty: num(r.quantity), extracted_qty: num(r.extracted_qty), unit_price: num(r.unit_price), expected_cod: num(r.expected_cod), mapping_status: text(r.mapping_status), stock_qty: num(r.stock_qty), stock_status: text(r.stock_status), raw_product_text: text(r.raw_product_text), raw_product_text_norm: text(r.raw_product_text_norm), parser_confidence: num(r.parser_confidence), match_method: text(r.match_method), candidate_skus: r.candidate_skus, evidence_sources: r.evidence_sources, reject_reason: text(r.reject_reason) }; }
function normalizeOrder(r: Record<string, unknown>, items: LiveOrderItem[]): LiveOrder { const sourcePayload = (() => { if (r.source_payload && typeof r.source_payload === "object") return r.source_payload as Record<string, unknown>; if (typeof r.source_payload === "string") { try { const parsed = JSON.parse(r.source_payload); return parsed && typeof parsed === "object" ? parsed as Record<string, unknown> : {}; } catch { return {}; } } return {}; })(); const raw = text(r.source_text ?? r.clean_text ?? sourcePayload.raw_text); const chat = timeline(r.chat_timeline ?? sourcePayload.chat_timeline ?? raw); const thread = text(r.source_chat_id); const cod = num(r.cod_amount) ?? num(r.expected_cod); const orderTime = text(r.order_time); return { id: num(r.id) ?? 0, upsert_key: text(r.upsert_key), order_number: text(r.order_number) ?? `#${r.id ?? "unknown"}`, order_date: orderTime?.slice(0, 10) ?? text(r.created_at)?.slice(0, 10) ?? null, order_time: orderTime, order_time_display: text(r.order_time_display), created_at: text(r.created_at), updated_at: text(r.updated_at), customer_name: text(r.customer_name ?? r.facebook_name), facebook_name: text(r.facebook_name), phone: text(r.phone), full_address: text(r.full_address), address_line_1: text(r.address_line_1), address_line_2: text(r.address_line_2), district: text(r.district), amphoe: text(r.amphoe), province: text(r.province), zipcode: text(r.zipcode), address_display_packer: text(r.full_address), page_name: text(r.page_name), page_id: text(r.page_id), thread_id: thread, threadId: thread, recipient_id: text(r.recipient_id), cod_amount: cod, expected_cod: num(r.expected_cod) ?? cod, sku: items[0]?.sku ?? null, th_name: items[0]?.th_name ?? null, emoji: items[0]?.emoji ?? null, display_for_packer: items.map(i => i.display_for_packer ?? i.label_display ?? i.product_name ?? i.raw_product_text ?? i.sku ?? "").filter(Boolean).join("\n") || null, label_display: items[0]?.label_display ?? null, telegram_status: text(r.view_status), order_status: text(r.order_status), audit_status: text(r.mapping_status), audit_flags: text(r.warning_text), cod_check_status: text(r.cod_check_status) ?? (cod == null ? "CHECK" : "PASS"), is_ready_to_pack: text(r.mapping_status) === "MATCHED" && text(r.order_status) === "READY", telegram_message: text(r.telegram_body_view), telegram_copy_text: text(r.telegram_body_view), telegram_chat_id: text(r.telegram_view_chat_id), source_text: raw, raw_text_with_phone: raw, raw_text_with_phone_timed: raw, full_chunk_text: raw, chat_timeline: chat, items_json: items, items_text: items.map(i => i.display_for_packer ?? i.product_name ?? i.raw_product_text ?? i.sku ?? "").join("\n"), items_count: items.length, total_quantity: items.reduce((s, i) => s + Number(i.quantity ?? 0), 0), items }; }
async function orderRows(limit = 3000) { return supabaseGet<Array<Record<string, unknown>>>(`canonical_orders?select=*&order=created_at.desc&limit=${limit}`); }
async function itemRows(orderIds: number[]) {
  if (!orderIds.length) return [];
  return supabaseGet<Array<Record<string, unknown>>>(`canonical_order_items?select=*&order_id=in.(${orderIds.join(",")})&order=line_no.asc&limit=10000`);
}
export async function fetchLiveOrders(search?: string) {
  const rows = await orderRows();
  let items: Array<Record<string, unknown>> = [];
  try {
    items = await itemRows(rows.map(r => Number(r.id)).filter(Number.isFinite));
  } catch (error) {
    // An item schema/query problem must not hide the canonical order header.
    // The UI can still show all orders and the error is available in server logs.
    console.error("[Supabase] canonical_order_items read failed; loading orders without items", error instanceof Error ? error.message : error);
  }
  const grouped = new Map<number, LiveOrderItem[]>();
  for (const item of items) { const n = Number(item.order_id); if (Number.isFinite(n)) grouped.set(n, [...(grouped.get(n) ?? []), normalizeItem(item)]); }
  const q = search?.trim().toLowerCase();
  return rows.map(r => normalizeOrder(r, grouped.get(Number(r.id)) ?? [])).filter(o => !q || JSON.stringify(o).toLowerCase().includes(q));
}
export function getLiveOrderStats(orders: LiveOrder[]): LiveOrderStats { return { total: orders.length, mapped: orders.filter(o => o.is_ready_to_pack).length, review: orders.filter(o => !o.is_ready_to_pack).length, codCheck: orders.filter(o => o.cod_check_status !== "PASS").length, sent: orders.filter(o => o.telegram_status === "SENT").length, pages: new Set(orders.map(o => o.page_id).filter(Boolean)).size }; }
export async function fetchLiveThreads(search?: string) { const orders = await fetchLiveOrders(search); const map = new Map<string, LiveThread>(); for (const order of orders) { const key = `${order.page_id ?? ""}:${order.thread_id ?? order.order_number}`; const current = map.get(key) ?? { key, pageName: order.page_name ?? "ไม่ระบุเพจ", pageId: order.page_id, threadId: order.thread_id, customerId: order.recipient_id ?? null, latestAt: order.created_at, latestOrderNumber: order.order_number, customerName: order.customer_name, preview: order.source_text ?? order.display_for_packer ?? "", orderCount: 0, unread: false, sentCount: 0, messageCount: 0, customerMessages: 0, pageMessages: 0, orderSignals: 0, snippets: [], orders: [], chatTimeline: [], searchText: "" }; current.orders.push(order); current.orderCount++; current.messageCount += order.chat_timeline.length; current.customerMessages = (current.customerMessages ?? 0) + order.chat_timeline.filter(x => !/เพจ|admin|แอดมิน/i.test(x)).length; current.pageMessages = (current.pageMessages ?? 0) + order.chat_timeline.filter(x => /เพจ|admin|แอดมิน/i.test(x)).length; current.orderSignals = current.orderCount; current.snippets = [...(current.snippets ?? []), ...order.chat_timeline.slice(0, 3)]; current.chatTimeline.push(...order.chat_timeline); current.searchText += ` ${order.customer_name ?? ""} ${order.source_text ?? ""} ${order.order_number}`; map.set(key, current); } return Array.from(map.values()).sort((a, b) => String(b.latestAt).localeCompare(String(a.latestAt))); }
export async function fetchExternalChatMessages(pageId: string, threadId: string): Promise<ExternalChatMessage[]> { const orders = (await fetchLiveOrders()).filter(o => o.page_id === pageId && o.thread_id === threadId); return orders.flatMap(o => o.chat_timeline.map((line, i) => { const outbound = /เพจ|admin|แอดมิน/i.test(line); return { id: o.id * 10000 + i, providerMessageId: null, pageId, pageName: o.page_name, threadId, senderId: o.recipient_id ?? "", senderName: o.customer_name, customerName: o.customer_name, sender_name: o.customer_name, customer_name: o.customer_name, speaker_type: outbound ? "page" : "customer", senderType: outbound ? "page" : "customer", side: outbound ? "right" : "left", direction: outbound ? "outbound" : "inbound", text: line, message_text: line, attachmentsJson: null, occurredAt: o.order_time, occurred_at: o.order_time, source_created_at: o.created_at, createdAt: o.created_at, source_message_id: null, dedupe_key: `:` }; })); }
export async function fetchConversationEvidence(pageId: string, threadId: string) { return fetchExternalChatMessages(pageId, threadId); }
export async function fetchDailyChatOrderSummary(date: string) { const orders = await fetchDailyOrderHistory(date); const threads = await fetchLiveThreads(); const dayThreads = threads.filter(t => t.orders.some(o => o.order_date === date)); return { date, total: orders.total, orders: orders.orders, threads: dayThreads, totalMessages: dayThreads.reduce((s, t) => s + t.messageCount, 0), customerMessages: dayThreads.reduce((s, t) => s + t.chatTimeline.filter(x => !/เพจ|admin|แอดมิน/i.test(x)).length, 0), pageMessages: dayThreads.reduce((s, t) => s + t.chatTimeline.filter(x => /เพจ|admin|แอดมิน/i.test(x)).length, 0), threadCount: dayThreads.length, orderSignalThreads: dayThreads.filter(t => t.orderCount > 0).length }; }
export async function fetchDailyOrderHistory(date: string, search?: string) { const orders = (await fetchLiveOrders(search)).filter(o => (o.order_date ?? o.created_at?.slice(0, 10)) === date); return { date, total: orders.length, orders }; }
export async function fetchStockProducts(): Promise<StockProduct[]> { const products = await supabaseGet<Array<Record<string, unknown>>>("product_master?select=*&order=sku.asc&limit=5000"); const [inventoryResult, aliasesResult] = await Promise.allSettled([supabaseGet<Array<Record<string, unknown>>>("inventory?select=*&limit=5000"), supabaseGet<Array<Record<string, unknown>>>("product_aliases?select=*&mapping_status=eq.APPROVED&limit=10000")]); const inventory = inventoryResult.status === "fulfilled" ? inventoryResult.value : []; const aliases = aliasesResult.status === "fulfilled" ? aliasesResult.value : []; const inv = new Map(inventory.map(r => [String(r.product_id), r])); const alias = new Map<string, string>(); for (const a of aliases) { const k = String(a.product_id); alias.set(k, [...(alias.get(k)?.split(", ") ?? []), String(a.alias_text ?? "")].filter(Boolean).join(", ")); } return products.map(r => { const i = inv.get(String(r.id)); return { id: Number(r.id), sku: String(r.sku ?? ""), label: String(r.label_display ?? r.display_for_packer ?? r.name_standard ?? r.sku ?? ""), price: num(r.unit_price), emoji: text(r.emoji), aliases: alias.get(String(r.id)) ?? null, thName: text(r.th_name), stockQty: num(i?.stock_qty), stockStatus: text(i?.stock_status), status: text(r.status), updatedAt: text(i?.updated_at ?? r.updated_at) }; }); }
export async function fetchStockWarnings(): Promise<StockWarning[]> { const p = await supabaseGet<Array<Record<string, unknown>>>("product_master?select=sku,th_name,label_display&limit=5000"); const seen = new Set<string>(); const warnings: StockWarning[] = []; for (const r of p) { const sku = text(r.sku); if (!sku) warnings.push({ kind: "missing_sku", sku: null, label: text(r.th_name ?? r.label_display) }); else if (seen.has(sku)) warnings.push({ kind: "duplicate_sku", sku, label: text(r.th_name ?? r.label_display) }); else seen.add(sku); } return warnings; }
export async function updateStockProduct(id: number, input: { stockQty?: number; stockStatus?: string; labelDisplay?: string; unitPrice?: number }) { const { baseUrl, key } = config(); if (input.labelDisplay !== undefined || input.unitPrice !== undefined) { const body: Record<string, unknown> = {}; if (input.labelDisplay !== undefined) body.label_display = input.labelDisplay; if (input.unitPrice !== undefined) body.unit_price = input.unitPrice; await fetch(`${baseUrl}/rest/v1/product_master?id=eq.${id}`, { method: "PATCH", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); } if (input.stockQty !== undefined || input.stockStatus !== undefined) { const body: Record<string, unknown> = {}; if (input.stockQty !== undefined) body.stock_qty = input.stockQty; if (input.stockStatus !== undefined) body.stock_status = input.stockStatus; await fetch(`${baseUrl}/rest/v1/inventory?product_id=eq.${id}`, { method: "PATCH", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); } return fetchStockProducts(); }
export async function updateProductMapAlias(sku: string, alias: string) { const products = await supabaseGet<Array<{ id: number }>>(`product_master?select=id&sku=eq.${encodeURIComponent(sku)}&limit=1`); const product = products[0]; if (!product) throw new Error(`SKU not found: ${sku}`); const { baseUrl, key } = config(); await fetch(`${baseUrl}/rest/v1/product_aliases`, { method: "POST", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json", Prefer: "resolution=merge-duplicates" }, body: JSON.stringify({ product_id: product.id, alias_text: alias.trim(), alias_norm: alias.trim().toLowerCase(), mapping_status: "APPROVED" }) }); return { ok: true, sku, alias: alias.trim() }; }
export async function fetchOrdersForThread(pageId: string, threadId: string) { return (await fetchLiveOrders()).filter(o => o.page_id === pageId && o.thread_id === threadId); }

export async function listCanonicalAliases() { return supabaseGet<Array<Record<string, unknown>>>("product_aliases?select=*&order=updated_at.desc&limit=10000"); }
export async function createCanonicalAlias(input: { alias: string; canonicalSku: string; canonicalLabel: string }) { const products = await supabaseGet<Array<{ id: number }>>(`product_master?select=id&sku=eq.${encodeURIComponent(input.canonicalSku)}&limit=1`); const product = products[0]; if (!product) throw new Error(`SKU not found: ${input.canonicalSku}`); await supabasePost("product_aliases", { product_id: product.id, alias_text: input.alias.trim(), alias_norm: input.alias.trim().toLowerCase(), mapping_status: "APPROVED", note: input.canonicalLabel }); return listCanonicalAliases(); }
export async function updateCanonicalAlias(input: { id: number; alias: string; canonicalSku: string; canonicalLabel: string; isActive?: boolean }) { const products = await supabaseGet<Array<{ id: number }>>(`product_master?select=id&sku=eq.${encodeURIComponent(input.canonicalSku)}&limit=1`); const { baseUrl, key } = config(); const body = { product_id: products[0]?.id ?? null, alias_text: input.alias.trim(), alias_norm: input.alias.trim().toLowerCase(), mapping_status: input.isActive === false ? "REJECTED" : "APPROVED", note: input.canonicalLabel }; await fetch(`${baseUrl}/rest/v1/product_aliases?id=eq.${input.id}`, { method: "PATCH", headers: { apikey: key, Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify(body) }); return listCanonicalAliases(); }
