-- Generated only from pasted_content_4.txt plus exact Alien/parser fields.
-- All fields are nullable by design. upsert_key remains the only required key.
-- Do not rename or remove these columns after applying.
begin;

alter table public.st_orders add column if not exists facebook_name text;
alter table public.st_orders add column if not exists threadId text;
alter table public.st_orders add column if not exists time_th text;
alter table public.st_orders add column if not exists order_date text;
alter table public.st_orders add column if not exists order_time text;
alter table public.st_orders add column if not exists order_time_display text;
alter table public.st_orders add column if not exists order_time_source text;
alter table public.st_orders add column if not exists page_name text;
alter table public.st_orders add column if not exists order_number text;
alter table public.st_orders add column if not exists cod_amount numeric;
alter table public.st_orders add column if not exists customer_name text;
alter table public.st_orders add column if not exists phone text;
alter table public.st_orders add column if not exists extracted_phone text;
alter table public.st_orders add column if not exists address_display_packer text;
alter table public.st_orders add column if not exists addressclean text;
alter table public.st_orders add column if not exists short_address text;
alter table public.st_orders add column if not exists district text;
alter table public.st_orders add column if not exists amphoe text;
alter table public.st_orders add column if not exists province text;
alter table public.st_orders add column if not exists zipcode text;
alter table public.st_orders add column if not exists line_no text;
alter table public.st_orders add column if not exists product_id text;
alter table public.st_orders add column if not exists sku text;
alter table public.st_orders add column if not exists product_name text;
alter table public.st_orders add column if not exists th_name text;
alter table public.st_orders add column if not exists quantity text;
alter table public.st_orders add column if not exists unit_price text;
alter table public.st_orders add column if not exists line_total text;
alter table public.st_orders add column if not exists emoji text;
alter table public.st_orders add column if not exists display_for_packer text;
alter table public.st_orders add column if not exists alias text;
alter table public.st_orders add column if not exists alias_norm text;
alter table public.st_orders add column if not exists qty text;
alter table public.st_orders add column if not exists extracted_qty text;
alter table public.st_orders add column if not exists extracted_emoji text;
alter table public.st_orders add column if not exists expected_cod numeric;
alter table public.st_orders add column if not exists lock_status text;
alter table public.st_orders add column if not exists order_status text;
alter table public.st_orders add column if not exists page_id text;
alter table public.st_orders add column if not exists recipient_id text;
alter table public.st_orders add column if not exists thread_id text;
alter table public.st_orders add column if not exists day_of_week text;
alter table public.st_orders add column if not exists created_at text;
alter table public.st_orders add column if not exists updated_at text;
alter table public.st_orders add column if not exists assigned_hashtag text;
alter table public.st_orders add column if not exists sniper_x_text_clean text;
alter table public.st_orders add column if not exists clean_text text;
alter table public.st_orders add column if not exists single_cleaned_block text;
alter table public.st_orders add column if not exists message_id text;
alter table public.st_orders add column if not exists bubble_window text;
alter table public.st_orders add column if not exists raw_text text;
alter table public.st_orders add column if not exists final_display_for_packer text;
alter table public.st_orders add column if not exists raw_text_with_phone text;
alter table public.st_orders add column if not exists display_for_ku text;
alter table public.st_orders add column if not exists full_chunk_text text;
alter table public.st_orders add column if not exists chat_timeline jsonb;
alter table public.st_orders add column if not exists has_phone boolean;
alter table public.st_orders add column if not exists has_cod boolean;
alter table public.st_orders add column if not exists telegram_sent boolean;
alter table public.st_orders add column if not exists product_lines text;
alter table public.st_orders add column if not exists parsed_products jsonb;
alter table public.st_orders add column if not exists primary_quantity text;
alter table public.st_orders add column if not exists unit text;
alter table public.st_orders add column if not exists residual_parser_status text;
alter table public.st_orders add column if not exists chat_timeline_count text;
alter table public.st_orders add column if not exists normalized_chat_timeline jsonb;
alter table public.st_orders add column if not exists extracted_sku text;
alter table public.st_orders add column if not exists extracted_product_raw text;
alter table public.st_orders add column if not exists product_copy_text text;
alter table public.st_orders add column if not exists product_display_for_packer text;
alter table public.st_orders add column if not exists product_display_candidates jsonb;
alter table public.st_orders add column if not exists mapping_status text;
alter table public.st_orders add column if not exists source_logic text;
alter table public.st_orders add column if not exists routing_tag_backup text;
alter table public.st_orders add column if not exists is_safety_white boolean;
alter table public.st_orders add column if not exists telegram_final_mapped text;
alter table public.st_orders add column if not exists product_source text;
alter table public.st_orders add column if not exists product_evidence jsonb;
alter table public.st_orders add column if not exists raw_product_evidence jsonb;
alter table public.st_orders add column if not exists product_backup_1 text;
alter table public.st_orders add column if not exists product_backup_2 text;
alter table public.st_orders add column if not exists full_address text;
alter table public.st_orders add column if not exists full_address_backup_1 text;
alter table public.st_orders add column if not exists full_address_backup_2 text;
alter table public.st_orders add column if not exists address_candidates jsonb;
alter table public.st_orders add column if not exists address_source text;
alter table public.st_orders add column if not exists address_completeness jsonb;
alter table public.st_orders add column if not exists final_address_for_bill text;
alter table public.st_orders add column if not exists telegram_message text;
alter table public.st_orders add column if not exists telegram_copy_text text;
alter table public.st_orders add column if not exists telegram_body jsonb;
alter table public.st_orders add column if not exists master_display_for_packer text;

alter table public.st_orders alter column upsert_key set not null;
alter table public.st_orders drop constraint if exists bb_orders_upsert_key_not_blank;
alter table public.st_orders add constraint bb_orders_upsert_key_not_blank check (length(btrim(upsert_key)) > 0);

commit;

-- columns listed: 93
